/* LimeGui.java */
package gui;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import javax.swing.KeyStroke;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.UndoableEditEvent;
import javax.swing.event.UndoableEditListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.DefaultEditorKit;
import javax.swing.text.JTextComponent;
import javax.swing.undo.CannotRedoException;
import javax.swing.undo.CannotUndoException;
import javax.swing.undo.UndoManager;
import tools.FileIO;
import tools.StrTools;
import tools.SyntaxColorTools;

/**
 * @author Oliver Chu, UC Berkeley EECS Major.
 */
public class LimeGui extends javax.swing.JFrame {
    //<editor-fold defaultstate="collapsed" desc="Class field declarations">
    private TabManager tabManageObj = new TabManager();
    private FileMenuManager fileManageObj = new FileMenuManager();
    private FindReplaceManager findReplaceObj = new FindReplaceManager();
    private Font textEditFont = new Font("Courier New", 0, 13);
    private ButtonGroup findTextDirectionButtonGroup;
    private ButtonGroup findTextDirectionButtonGroup2;
    private UndoManagerTeam undoManageTeam = new UndoManagerTeam();
    private UndoAction undoActionObj = new UndoAction();
    private RedoAction redoActionObj = new RedoAction();
    private JMenuItem undoItem;
    private JMenuItem redoItem;
    private SyntaxColorTools sct = new SyntaxColorTools();

    /** Use this class constructor to add startup actions. */
    //<editor-fold defaultstate="collapsed" desc="Class constructor">
    public LimeGui() {
        super();
        initComponents();
        tabManageObj.addTab();
        //<editor-fold defaultstate="collapsed" desc="Add buttongroups for Find/Replace">
        findTextDirectionButtonGroup = new ButtonGroup();
        findTextDirectionButtonGroup.add(searchUpRadioButton);
        findTextDirectionButtonGroup.add(searchDownRadioButton);
        findTextDirectionButtonGroup2 = new ButtonGroup();
        findTextDirectionButtonGroup2.add(searchUpRadioButton2);
        findTextDirectionButtonGroup2.add(searchDownRadioButton2);
        //</editor-fold>
        //<editor-fold defaultstate="collapsed" desc="Add Undo/Redo menu items">
        undoItem = new JMenuItem(undoActionObj);
        undoItem.setText("Undo");
        undoItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_Z,
                 InputEvent.CTRL_MASK));
        redoItem = new JMenuItem(redoActionObj);
        redoItem.setText("Redo");
        redoItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_Y,
                 InputEvent.CTRL_MASK));
        editMenu.add(redoItem,0);
        editMenu.add(undoItem,0);
        //</editor-fold>
    }
    //</editor-fold>

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        findTextFrame = new javax.swing.JFrame();
        searchForLabel = new javax.swing.JLabel();
        query = new javax.swing.JTextField();
        findTextButton = new javax.swing.JButton();
        countOccurrencesButton = new javax.swing.JButton();
        searchUpRadioButton = new javax.swing.JRadioButton();
        searchDownRadioButton = new javax.swing.JRadioButton();
        matchCaseCheckBox = new javax.swing.JCheckBox();
        wrapDocumentAroundCheckBox = new javax.swing.JCheckBox();
        findReplaceFrame = new javax.swing.JFrame();
        searchForLabel2 = new javax.swing.JLabel();
        query2 = new javax.swing.JTextField();
        findTextButton2 = new javax.swing.JButton();
        countOccurrencesButton2 = new javax.swing.JButton();
        searchUpRadioButton2 = new javax.swing.JRadioButton();
        searchDownRadioButton2 = new javax.swing.JRadioButton();
        matchCaseCheckBox2 = new javax.swing.JCheckBox();
        wrapDocumentAroundCheckBox2 = new javax.swing.JCheckBox();
        replaceWithLabel = new javax.swing.JLabel();
        replaceTextField = new javax.swing.JTextField();
        replaceButton = new javax.swing.JButton();
        replaceAllButton = new javax.swing.JButton();
        changeFontFrame = new javax.swing.JFrame();
        fontField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        changeFontButton = new javax.swing.JButton();
        mainTabbedPane = new javax.swing.JTabbedPane();
        topMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newFileItem = new javax.swing.JMenuItem();
        openFileItem = new javax.swing.JMenuItem();
        saveFileItem = new javax.swing.JMenuItem();
        saveFileAsItem = new javax.swing.JMenuItem();
        separator1 = new javax.swing.JPopupMenu.Separator();
        quitItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutItem = new javax.swing.JMenuItem();
        copyItem = new javax.swing.JMenuItem();
        pasteItem = new javax.swing.JMenuItem();
        selectAllItem = new javax.swing.JMenuItem();
        separator2 = new javax.swing.JPopupMenu.Separator();
        findTextItem = new javax.swing.JMenuItem();
        findReplaceItem = new javax.swing.JMenuItem();
        separator4 = new javax.swing.JPopupMenu.Separator();
        changeFontItem = new javax.swing.JMenuItem();
        tabMenu = new javax.swing.JMenu();
        newTabItem = new javax.swing.JMenuItem();
        closeTabItem = new javax.swing.JMenuItem();
        closeAllTabsItem = new javax.swing.JMenuItem();
        separator3 = new javax.swing.JPopupMenu.Separator();
        switchFirstTabItem = new javax.swing.JMenuItem();
        switchLastTabItem = new javax.swing.JMenuItem();

        findTextFrame.setTitle("Find text");

        searchForLabel.setText("Search for:");

        query.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                queryKeyPressed(evt);
            }
        });

        findTextButton.setText("Find it");
        findTextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findTextButtonActionPerformed(evt);
            }
        });

        countOccurrencesButton.setText("Count Occurrences");
        countOccurrencesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countOccurrencesButtonActionPerformed(evt);
            }
        });

        searchUpRadioButton.setText("Search Up");

        searchDownRadioButton.setSelected(true);
        searchDownRadioButton.setText("Search Down");

        matchCaseCheckBox.setText("Match Case");

        wrapDocumentAroundCheckBox.setSelected(true);
        wrapDocumentAroundCheckBox.setText("Wrap Document Around");

        javax.swing.GroupLayout findTextFrameLayout = new javax.swing.GroupLayout(findTextFrame.getContentPane());
        findTextFrame.getContentPane().setLayout(findTextFrameLayout);
        findTextFrameLayout.setHorizontalGroup(
            findTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findTextFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(findTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(findTextFrameLayout.createSequentialGroup()
                        .addComponent(query, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(findTextFrameLayout.createSequentialGroup()
                        .addGroup(findTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchForLabel)
                            .addGroup(findTextFrameLayout.createSequentialGroup()
                                .addComponent(findTextButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(countOccurrencesButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, findTextFrameLayout.createSequentialGroup()
                                .addGroup(findTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchUpRadioButton)
                                    .addComponent(searchDownRadioButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addGroup(findTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wrapDocumentAroundCheckBox)
                                    .addComponent(matchCaseCheckBox))))
                        .addGap(24, 24, 24))))
        );
        findTextFrameLayout.setVerticalGroup(
            findTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findTextFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchForLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(query, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(findTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findTextButton)
                    .addComponent(countOccurrencesButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(findTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchUpRadioButton)
                    .addComponent(matchCaseCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(findTextFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchDownRadioButton)
                    .addComponent(wrapDocumentAroundCheckBox))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        findReplaceFrame.setTitle("Find and Replace Text");

        searchForLabel2.setText("Search for:");

        query2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                query2KeyPressed(evt);
            }
        });

        findTextButton2.setText("Find it");
        findTextButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findTextButton2ActionPerformed(evt);
            }
        });

        countOccurrencesButton2.setText("Count Occurrences");
        countOccurrencesButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countOccurrencesButton2ActionPerformed(evt);
            }
        });

        searchUpRadioButton2.setText("Search Up");

        searchDownRadioButton2.setSelected(true);
        searchDownRadioButton2.setText("Search Down");

        matchCaseCheckBox2.setText("Match Case");

        wrapDocumentAroundCheckBox2.setSelected(true);
        wrapDocumentAroundCheckBox2.setText("Wrap Document Around");

        replaceWithLabel.setText("Replace With:");

        replaceButton.setText("Replace Current");
        replaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceButtonActionPerformed(evt);
            }
        });

        replaceAllButton.setText("Replace All");
        replaceAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceAllButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout findReplaceFrameLayout = new javax.swing.GroupLayout(findReplaceFrame.getContentPane());
        findReplaceFrame.getContentPane().setLayout(findReplaceFrameLayout);
        findReplaceFrameLayout.setHorizontalGroup(
            findReplaceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findReplaceFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(findReplaceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(findReplaceFrameLayout.createSequentialGroup()
                        .addGroup(findReplaceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchUpRadioButton2)
                            .addComponent(searchDownRadioButton2))
                        .addGap(18, 18, 18)
                        .addGroup(findReplaceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wrapDocumentAroundCheckBox2)
                            .addComponent(matchCaseCheckBox2))
                        .addContainerGap())
                    .addGroup(findReplaceFrameLayout.createSequentialGroup()
                        .addGroup(findReplaceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchForLabel2)
                            .addGroup(findReplaceFrameLayout.createSequentialGroup()
                                .addComponent(findTextButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(countOccurrencesButton2)))
                        .addGap(24, 24, 24))
                    .addGroup(findReplaceFrameLayout.createSequentialGroup()
                        .addComponent(replaceWithLabel)
                        .addContainerGap(209, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, findReplaceFrameLayout.createSequentialGroup()
                        .addGroup(findReplaceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(replaceTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(query2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(findReplaceFrameLayout.createSequentialGroup()
                        .addComponent(replaceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(replaceAllButton)
                        .addContainerGap(74, Short.MAX_VALUE))))
        );
        findReplaceFrameLayout.setVerticalGroup(
            findReplaceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findReplaceFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchForLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(query2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(findReplaceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findTextButton2)
                    .addComponent(countOccurrencesButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(replaceWithLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(replaceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(findReplaceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(replaceButton)
                    .addComponent(replaceAllButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(findReplaceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(findReplaceFrameLayout.createSequentialGroup()
                        .addComponent(searchUpRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchDownRadioButton2))
                    .addGroup(findReplaceFrameLayout.createSequentialGroup()
                        .addComponent(matchCaseCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wrapDocumentAroundCheckBox2)))
                .addContainerGap())
        );

        changeFontFrame.setTitle("Change Font");

        fontField.setText("Courier New");

        jLabel1.setText("Font:");

        jLabel2.setText("Suggested Windows Fonts: Courier New, Lucida Console, Consolas");

        jLabel3.setText("Suggested Mac Fonts: Andale Mono, Monaco, Menlo ");

        jLabel4.setText("Suggested Linux Fonts: Andale Mono, Courier New, FreeMono, Nimbus Mono, DejaVu Sans Mono, Liberation Mono");

        changeFontButton.setText("Change");
        changeFontButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeFontButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout changeFontFrameLayout = new javax.swing.GroupLayout(changeFontFrame.getContentPane());
        changeFontFrame.getContentPane().setLayout(changeFontFrameLayout);
        changeFontFrameLayout.setHorizontalGroup(
            changeFontFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeFontFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(changeFontFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changeFontFrameLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fontField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changeFontButton))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        changeFontFrameLayout.setVerticalGroup(
            changeFontFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeFontFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(changeFontFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fontField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeFontButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JLime - A Text Editor for Editing Java - By Oliver Chu");

        fileMenu.setText("File");

        newFileItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newFileItem.setText("New File");
        newFileItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileItemActionPerformed(evt);
            }
        });
        fileMenu.add(newFileItem);

        openFileItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openFileItem.setText("Open File");
        openFileItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileItemActionPerformed(evt);
            }
        });
        fileMenu.add(openFileItem);

        saveFileItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveFileItem.setText("Save File");
        saveFileItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveFileItem);

        saveFileAsItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        saveFileAsItem.setText("Save File As...");
        saveFileAsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileAsItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveFileAsItem);
        fileMenu.add(separator1);

        quitItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        quitItem.setText("Quit");
        quitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitItemActionPerformed(evt);
            }
        });
        fileMenu.add(quitItem);

        topMenuBar.add(fileMenu);

        editMenu.setText("Edit");

        cutItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        cutItem.setText("Cut");
        cutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutItemActionPerformed(evt);
            }
        });
        editMenu.add(cutItem);

        copyItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        copyItem.setText("Copy");
        copyItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyItemActionPerformed(evt);
            }
        });
        editMenu.add(copyItem);

        pasteItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        pasteItem.setText("Paste");
        pasteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteItemActionPerformed(evt);
            }
        });
        editMenu.add(pasteItem);

        selectAllItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        selectAllItem.setText("Select All");
        selectAllItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllItemActionPerformed(evt);
            }
        });
        editMenu.add(selectAllItem);
        editMenu.add(separator2);

        findTextItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        findTextItem.setText("Find...");
        findTextItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findTextItemActionPerformed(evt);
            }
        });
        editMenu.add(findTextItem);

        findReplaceItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        findReplaceItem.setText("Find / Replace...");
        findReplaceItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findReplaceItemActionPerformed(evt);
            }
        });
        editMenu.add(findReplaceItem);
        editMenu.add(separator4);

        changeFontItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        changeFontItem.setText("Change Font");
        changeFontItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeFontItemActionPerformed(evt);
            }
        });
        editMenu.add(changeFontItem);

        topMenuBar.add(editMenu);

        tabMenu.setText("Tabs");

        newTabItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        newTabItem.setText("New Tab");
        newTabItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTabItemActionPerformed(evt);
            }
        });
        tabMenu.add(newTabItem);

        closeTabItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        closeTabItem.setText("Close Current Tab");
        closeTabItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeTabItemActionPerformed(evt);
            }
        });
        tabMenu.add(closeTabItem);

        closeAllTabsItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        closeAllTabsItem.setText("Close All Tabs");
        closeAllTabsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAllTabsItemActionPerformed(evt);
            }
        });
        tabMenu.add(closeAllTabsItem);
        tabMenu.add(separator3);

        switchFirstTabItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        switchFirstTabItem.setText("Switch to First Tab");
        switchFirstTabItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchFirstTabItemActionPerformed(evt);
            }
        });
        tabMenu.add(switchFirstTabItem);

        switchLastTabItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_9, java.awt.event.InputEvent.CTRL_MASK));
        switchLastTabItem.setText("Switch to Last Tab");
        switchLastTabItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchLastTabItemActionPerformed(evt);
            }
        });
        tabMenu.add(switchLastTabItem);

        topMenuBar.add(tabMenu);

        setJMenuBar(topMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void newTabItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTabItemActionPerformed
    tabManageObj.addTab();
}//GEN-LAST:event_newTabItemActionPerformed

private void closeTabItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeTabItemActionPerformed
    tabManageObj.removeTab(tabManageObj.getCurrentTabIndex());
}//GEN-LAST:event_closeTabItemActionPerformed

private void closeAllTabsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAllTabsItemActionPerformed
    mainTabbedPane.removeAll();
    tabManageObj = new TabManager();
}//GEN-LAST:event_closeAllTabsItemActionPerformed

private void switchFirstTabItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchFirstTabItemActionPerformed
    tabManageObj.switchToFirstTab();
}//GEN-LAST:event_switchFirstTabItemActionPerformed

private void switchLastTabItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchLastTabItemActionPerformed
    tabManageObj.switchToLastTab();
}//GEN-LAST:event_switchLastTabItemActionPerformed

private void cutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutItemActionPerformed
    tabManageObj.getSelectedTextPane().cut();
}//GEN-LAST:event_cutItemActionPerformed

private void copyItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyItemActionPerformed
    tabManageObj.getSelectedTextPane().copy();
}//GEN-LAST:event_copyItemActionPerformed

private void pasteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteItemActionPerformed
    tabManageObj.getSelectedTextPane().paste();
}//GEN-LAST:event_pasteItemActionPerformed

private void selectAllItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllItemActionPerformed
    tabManageObj.getSelectedTextPane().selectAll();
}//GEN-LAST:event_selectAllItemActionPerformed

private void newFileItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileItemActionPerformed
    tabManageObj.resetCurrentTab();
}//GEN-LAST:event_newFileItemActionPerformed

private void quitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitItemActionPerformed
    System.exit(0);
}//GEN-LAST:event_quitItemActionPerformed

private void openFileItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileItemActionPerformed
    fileManageObj.runOpenDialog();
}//GEN-LAST:event_openFileItemActionPerformed

private void saveFileAsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileAsItemActionPerformed
    fileManageObj.runSaveAsDialog(tabManageObj.getSelectedTextPane().getText());
}//GEN-LAST:event_saveFileAsItemActionPerformed

private void saveFileItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileItemActionPerformed
    fileManageObj.runSaveDialog();
}//GEN-LAST:event_saveFileItemActionPerformed

private void queryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_queryKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        findReplaceObj.findText(false);
    }
}//GEN-LAST:event_queryKeyPressed

private void findTextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findTextButtonActionPerformed
    findReplaceObj.findText(false);
}//GEN-LAST:event_findTextButtonActionPerformed

private void countOccurrencesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countOccurrencesButtonActionPerformed
    findReplaceObj.countOccurrences(false);
}//GEN-LAST:event_countOccurrencesButtonActionPerformed

private void query2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_query2KeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        findReplaceObj.findText(true);
    }
}//GEN-LAST:event_query2KeyPressed

private void findTextButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findTextButton2ActionPerformed
    findReplaceObj.findText(true);
}//GEN-LAST:event_findTextButton2ActionPerformed

private void countOccurrencesButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countOccurrencesButton2ActionPerformed
    findReplaceObj.countOccurrences(false);
}//GEN-LAST:event_countOccurrencesButton2ActionPerformed

private void replaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceButtonActionPerformed
    findReplaceObj.replaceCurrent();
}//GEN-LAST:event_replaceButtonActionPerformed

private void replaceAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceAllButtonActionPerformed
    findReplaceObj.replaceAll();
}//GEN-LAST:event_replaceAllButtonActionPerformed

private void findTextItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findTextItemActionPerformed
    findTextFrame.pack();
    findTextFrame.setVisible(true);
}//GEN-LAST:event_findTextItemActionPerformed

private void findReplaceItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findReplaceItemActionPerformed
    findReplaceFrame.pack();
    findReplaceFrame.setVisible(true);
}//GEN-LAST:event_findReplaceItemActionPerformed

    private void changeFontItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeFontItemActionPerformed
        changeFontFrame.pack();
        changeFontFrame.setVisible(true);
    }//GEN-LAST:event_changeFontItemActionPerformed

    private void changeFontButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeFontButtonActionPerformed
        tabManageObj.setFont(new Font(fontField.getText(), 0, 13));
        Dialog.msgBox("Font changed.");
    }//GEN-LAST:event_changeFontButtonActionPerformed

//<editor-fold defaultstate="collapsed" desc="Private class FileMenuManager">
private class FileMenuManager {
    private void runOpenDialog() {
        setFileFilterToTextFiles();
        String workingDir = System.getProperty("user.dir");
        File currentDirObj = new File(workingDir);
        fileChooser.setCurrentDirectory(currentDirObj);
        int buttonChoice = fileChooser.showOpenDialog(null);
        if (buttonChoice == JFileChooser.APPROVE_OPTION) {
            File fileObj = fileChooser.getSelectedFile();
            if (!fileObj.exists()) {
                Dialog.errorBox("That file doesn't exist.", true);
            }
            String filePath = fileObj.getPath();
            String fileContents = FileIO.textFileToStr(filePath);
            tabManageObj.setCurrentFilePath(filePath);
            tabManageObj.getSelectedTextPane().setText(fileContents);
            new SyntaxColorTools().styleJavaCodeInDocument(
                                   tabManageObj.getSelectedTextPane(), 0);
            String fileName = FileIO.fullPathToFileName(filePath);
            tabManageObj.setCurrentTabTitle(fileName);
        }
    }
    
    private void setFileFilterToTextFiles() {
        fileChooser.resetChoosableFileFilters();
        FileNameExtensionFilter textFileFilter =
                        new FileNameExtensionFilter("Java File (.java)","java");
        FileNameExtensionFilter textFileFilter2 =
                          new FileNameExtensionFilter("Text File (.txt)","txt");
        fileChooser.addChoosableFileFilter(textFileFilter2);
        fileChooser.addChoosableFileFilter(textFileFilter);
    }
    
    private void runSaveAsDialog(String textContents) {
        setFileFilterToTextFiles();
        //Get the directory where the program is running from.
        String currentWorkingDir = System.getProperty("user.dir");
        File currentDirObj = new File(currentWorkingDir);
        fileChooser.setCurrentDirectory(currentDirObj);
        int buttonChoice = fileChooser.showSaveDialog(null);
        if (buttonChoice == JFileChooser.APPROVE_OPTION) {
            File fileObj = fileChooser.getSelectedFile();
            if (fileObj.exists()) {
                if (!Dialog.askBox("Replace selected file: " + fileObj.getName()
                                   + "?")) {
                    //Return if the user doesn't want to replace the file.
                    return;
                }
            }
            String filePath = fileObj.getPath();
            filePath = FileIO.addFileExtensionIfNeeded(filePath,".txt");
            FileIO.strToTextFile(textContents,filePath);
            tabManageObj.setCurrentFilePath(filePath);
            String fileName = FileIO.fullPathToFileName(filePath);
            tabManageObj.setCurrentTabTitle(fileName);
//            setSavedFile();
        }
    }
    
    private void runSaveDialog() {
        String filePath = tabManageObj.getCurrentFilePath();
        String text = tabManageObj.getSelectedTextPane().getText();
        if (filePath.isEmpty()) {
            runSaveAsDialog(text);
            return;
        }
        setFileFilterToTextFiles();
        FileIO.strToTextFile(text,filePath);
//      setSavedFile();
    }
}
//</editor-fold>

//<editor-fold defaultstate="collapsed" desc="Private class TabManager">
private class TabManager {
    //<editor-fold defaultstate="collapsed" desc="Field declarations">
    private ArrayList<JScrollPane> tabList = new ArrayList<JScrollPane>();
    private ArrayList<JTextPane> textPaneList = new ArrayList<JTextPane>();
    private ArrayList<String> filesBeingEdited = new ArrayList<String>();
    private ArrayList<CustomUndoableEditListener> editListeners =
            new ArrayList<CustomUndoableEditListener>();
    //</editor-fold>
    
    public void setFont(Font f) {
        for (JTextPane jtp : textPaneList) {
            jtp.setFont(f);
        }
    }
    
    private class KeyManager implements KeyListener {
        JTextPane tPane;
        public KeyManager(JTextPane tp) {
            tPane = tp;
        }
        
        @Override public void keyTyped(KeyEvent e) {}

        @Override public void keyPressed(KeyEvent e) {
            new SyntaxColorTools().styleJavaCodeInDocument(tPane, 0);
            alertBadSyntax(tPane);
        }

        @Override public void keyReleased(KeyEvent e) {
            if (e.getKeyCode() == KeyEvent.VK_TAB) {
                int caretPos = tPane.getCaretPosition();
                tPane.setText(tPane.getText().replace("\t", "    "));
                new SyntaxColorTools().styleJavaCodeInDocument(tPane, 0);
                tPane.setCaretPosition(caretPos + 3);
            }
        }
    }
    
    //<editor-fold defaultstate="collapsed" desc="Tab methods">
    private void addTab() {
        JScrollPane newScrollPane = new JScrollPane();
        JTextPane newTextPane = new JTextPane();
        newTextPane.setBackground(Color.BLACK);
        newTextPane.setForeground(Color.WHITE);
        newTextPane.setCaretColor(Color.WHITE);
        tools.SyntaxColorTools.addStylesToTextPane(newTextPane);
        newTextPane.addKeyListener(new KeyManager(newTextPane));
        newScrollPane.setViewportView(newTextPane);
        textPaneList.add(newTextPane);
        tabList.add(newScrollPane);
        mainTabbedPane.addTab("New File",newScrollPane);
        filesBeingEdited.add("");
        undoManageTeam.addManager();
        editListeners.add(new CustomUndoableEditListener());
        addPropertiesToTextPane(newTextPane);
        switchToLastTab();
    }
    
    void removeTab(int index) {
        if (isInBounds(index)) {
            mainTabbedPane.remove(index);
            tabList.remove(index);
            textPaneList.remove(index);
            filesBeingEdited.remove(index);
            undoManageTeam.removeManager(index);
            editListeners.remove(index);
        }
    }
    
    void resetCurrentTab() {
        if (getTabCount() == 0) {
            addTab();
            return;
        }
        getSelectedTextPane().setText("");
        setCurrentTabTitle("New File");
        setCurrentFilePath("");
    }
    
    int getTabCount() {
        return tabList.size();
    }
    
    int getCurrentTabIndex() {
        return mainTabbedPane.getSelectedIndex();
    }
    
    boolean isInBounds(int tabIndex) {
        return (tabIndex >= 0 && tabIndex < getTabCount());
    }
    
    void switchToLastTab() {
        int index = getTabCount() - 1;
        if (isInBounds(index)) {
            mainTabbedPane.setSelectedIndex(index);
        }
    }
    
    void switchToFirstTab() {
        if (isInBounds(0)) {
            mainTabbedPane.setSelectedIndex(0);
        }
    }
    
    void setCurrentTabTitle(String title) {
        mainTabbedPane.setTitleAt(getCurrentTabIndex(),title);
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="File name methods">
    private void setFilePathAt(int index,String name) {
        if (isInBounds(index)) {
            filesBeingEdited.set(index,name);
        }
    }
    
    private void setCurrentFilePath(String name) {
        setFilePathAt(getCurrentTabIndex(),name);
    }
    
    private String getFilePathAt(int index) {
        if (isInBounds(index)) {
            return filesBeingEdited.get(index);
        }
        return "";
    }
    
    private String getCurrentFilePath() {
        return getFilePathAt(getCurrentTabIndex());
    }
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="TextPane methods">
    private JTextPane getTextPaneAt(int index) {
        return textPaneList.get(index);
    }
    
    private JTextPane getSelectedTextPane() {
        if (getTabCount() == 0) {
            addTab();
            return textPaneList.get(0);
        }
        return textPaneList.get(getCurrentTabIndex());
    }
    
    private void addPropertiesToTextPane(JTextPane textPane) {
        textPane.setFont(textEditFont);
        //Remove the default Ctrl + H action because we want to use that for
        //the Find / Replace keyboard shortcut (accelerator).
        textPane.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_H,
                                   KeyEvent.CTRL_MASK),"none");
        //Remove the \r\n feature of the textPane and use \n only.
        //Despite various rumors on the Internet that you need to call this
        //every keypress or so, this is not true. Do it once and you're done.
        textPane.getDocument().
                 putProperty(DefaultEditorKit.EndOfLineStringProperty,"\n");
        //TODO : GIVE EACH TEXTPANE ITS OWN editListenObj.
        int lastIndex = editListeners.size() - 1;
        textPane.getDocument().addUndoableEditListener(
                               editListeners.get(lastIndex));
//        textPane.addFocusListener(new FocusAdapter() {
//            @Override
//            public void focusGained(FocusEvent evt) {
//                focusManageObj.currentTextPaneFocused();
//            }
//        });
    }
    
    private void focusCurrentTextPane() {
        getSelectedTextPane().requestFocusInWindow();
    }
    //</editor-fold>
    }
//</editor-fold>

//<editor-fold defaultstate="collapsed" desc="Private class UndoManagerTeam">
private class UndoManagerTeam {
    private ArrayList<UndoManager> undoManageTeam =
                                   new ArrayList<UndoManager>();
    
    private void addManager() {
        undoManageTeam.add(new UndoManager());
    }
    
    private void removeManager(int index) {
        undoManageTeam.remove(index);
    }
    
    private UndoManager getCurrentManager() {
        int currentIndex = tabManageObj.getCurrentTabIndex();
        return undoManageTeam.get(currentIndex);
    }
}
//</editor-fold>
    private void showFailure(JTextPane tPane, String failMsg) {
        tPane.setBackground(new Color(178, 34, 34));
        setTitle("Style Check Failed: " + failMsg);
    }
    
    private int stringSum(String x) {
        int sum = 0;
        for (char c : x.toCharArray()) {
            sum += c;
        }
        return sum;
    }
    
    private void alertBadSyntax(JTextPane tPane) {
        String txt = tPane.getText();
        if (!txt.endsWith("\n") && txt.length() > 5) {
            showFailure(tPane, "File must end with a newline. (\\n)");
            return;
        }
        String txt2 = "";
        /* Remove quotes from txt. We don't need to stylecheck Strings. */
        boolean isInsideQuotes = false;
        for (char c : txt.toCharArray()) {
            if (c == '"') {
                isInsideQuotes = !isInsideQuotes;
                if (isInsideQuotes) {
                    txt2 += '"';
                }
            }
            if (!isInsideQuotes) {
                txt2 += c;
            }
        }
        txt = txt2 + "    ";
        txt = txt.replace("\r", "\n");
        txt = txt.replace("\n\n", "\n");
        if (StrTools.countOccurrences(txt, "\n", false) > 2000) {
            showFailure(tPane,
                "File is too long for style61b. "
                + "Reduce it to 2000 lines or fewer.");
            return;
        }
        if (StrTools.countOccurrences(txt, "\n", false) > 5
            && !txt.contains(";")) {
            showFailure(tPane, "File has no semicolons.");
            return;
        }
        if (txt.contains("editor-fold")) {
            showFailure(tPane, "You cannot use Eclipse.");
            return;
        }
        int idx = -1;
        while (true) {
            idx = StrTools.search(txt, idx + 1, "P" + (char) (97));
            if (idx == -1) {
                break;
            }
            String slice = StrTools.slice(txt, idx, idx + 15);
            String slice2 = StrTools.slice(txt, idx, idx + 11);
            if (stringSum(slice) == 1458) {
                showFailure(tPane,
                    "Cannot extend an interface. Use inherits instead.");
                return;
            }
            if (stringSum(slice2) == 1048) {
                showFailure(tPane,
                    "Cannot instantiate generic type T. Use Object instead.");
                return;
            }
        }
        int i = 0;
        String[] lines = txt.split("\n");
        for (String line : lines) {
            if (!line.contains("}")
                && StrTools.countOccurrences(txt, ",", false) > 8
                && line.contains("(") && line.contains(")")) {
                showFailure(tPane,
                    "Method call or declaration has more than 8 "
                    + "arguments / parameters.");
                return;
            }
            if (line.length() > 80) {
                showFailure(tPane, "Line " + (i + 1)
                            + " is > 80 chars: "
                            + line);
                return;
            }
            if (line.contains("if") || line.contains("while") ||
                line.contains("for") || line.contains("switch") ||
                line.contains("else")) {
                if (!line.contains("{") && i + 1 < lines.length) {
                    if (!lines[i + 1].contains("{")) {
                        showFailure(tPane, "Control flow must use braces {}.");
                        return;
                    }
                }
            }
            i++;
        }
        if (!txt.contains("@author") && txt.length() > 100) {
            showFailure(tPane, "No @author tag in class doc comments.");
            return;
        }
        if (!txt.contains("/**") && txt.length() > 100) {
            showFailure(tPane, "No doc comments used.");
            return;
        }
        if (txt.contains("//")) {
            showFailure(tPane, "No // comments allowed.");
            return;
        }
        if (txt.contains("public boolean equals(")
            && !txt.contains("hashCode")) {
            showFailure(tPane,
                        "equals method defined without hashCode method.");
            return;
        }
        if (StrTools.countOccurrences(txt, "switch", false)
            > StrTools.countOccurrences(txt, "default", false)) {
            showFailure(tPane, "switch statement without default case.");
            return;
        }
        if (txt.contains(" == \"")) {
            showFailure(tPane, "Cannot compare Strings with ==.");
            return;
        }
        if (txt.contains("catch (RuntimeException") ||
            txt.contains("catch (Exception") ||
            txt.contains("catch (Throwable") ||
            txt.contains("catch (RuntimeError") ||
            txt.contains("catch (Error")) {
            showFailure(tPane, "Cannot catch any of these - Throwable,"
                        + " Exception, RuntimeError, Error, RuntimeException.");
            return;
        }
        for (String line : txt.split("\n")) {
            if (line.contains("import")
                && line.contains(".*")) {
                showFailure(tPane, "Do not use \"import something.*;\"");
                return;
            }
            line = line.replace(";", " ; ");
            line = line.replace("(", " ( ");
            line = line.replace(")", " ) ");
            line = line.replace(",", " , ");
            String[] tokens = line.split(" ");
            for (String tok : tokens) {
                tok = tok.trim();
                try {
                    int tAsInt = Integer.parseInt(tok);
                    if (tAsInt > 10 || tAsInt < -10) {
                        showFailure(tPane, "Magic number " + tAsInt
                            + " not allowed. Use static final variables.");
                        return;
                    }
                } catch (NumberFormatException ex) {
                    /* Do nothing. */
                }
            }
        }
        String[] ops = {"+", "-", "%", ">>", "<<", ">>>",
                        "^", "?", "&&", "||"};
        for (String op : ops) {
            txt2 = txt.replace("=", " ").replace("\n", " ").replace("++",
                               " + ").replace("--", " - ");
            if (StrTools.countOccurrences(txt2, op, false) !=
                StrTools.countOccurrences(txt2, " " + op + " ", false)) {
                showFailure(tPane, "Put spaces around operator " + op);
                return;
            }
        }
        for (String line : txt.split("\n")) {
            for (String op : ops) {
                if (line.endsWith(op)) {
                    showFailure(tPane, op + " should start on a new line.");
                    return;
                }
            }
        }
        txt2 = txt.replace("int", "").replace("String",
               "").replace("double", "").replace("float",
               "").replace("byte", "").replace("short",
               "").replace("char", "").replace("Object", "");
        if (StrTools.countOccurrences(txt2, "()", false)
            != StrTools.countOccurrences(txt2, "() ", false)) {
            showFailure(tPane, "Put spaces after casts and method calls.");
            return;
        }
        tPane.setBackground(Color.BLACK);
        setTitle("JLime - A Text Editor for Editing Java - By Oliver Chu");
    }

//<editor-fold defaultstate="collapsed" desc="Private class FindReplaceManager">
private class FindReplaceManager {
    private void findText(boolean isUsingSecondQuery) {
        String queryText;
        if (isUsingSecondQuery) {
            queryText = query2.getText();
        } else {
            queryText = query.getText();
        }
        if (queryText.isEmpty()) {
            Dialog.msgBox("Please specify some text to find.");
            return;
        }
        boolean isSearchingDownward;
        boolean isCaseSensitive;
        boolean isWrappedDocument;
        if (isUsingSecondQuery) {
            isSearchingDownward = searchDownRadioButton2.isSelected();
            isCaseSensitive = matchCaseCheckBox2.isSelected();
            isWrappedDocument = wrapDocumentAroundCheckBox2.isSelected();
        } else {
            isSearchingDownward = searchDownRadioButton.isSelected();
            isCaseSensitive = matchCaseCheckBox.isSelected();
            isWrappedDocument = wrapDocumentAroundCheckBox.isSelected();
        }
        JTextPane currentPane = tabManageObj.getSelectedTextPane();
        findAndSelectTextInTextComponent(currentPane,queryText,
                isWrappedDocument,isCaseSensitive,
                isSearchingDownward);
    }
    
    private void countOccurrences(boolean isUsingSecondQuery) {
        String queryText;
        if (isUsingSecondQuery) {
            queryText = query2.getText();
        }
        else {
            queryText = query.getText();
        }
        boolean isIgnoringCase;
        if (isUsingSecondQuery) {
            isIgnoringCase = !matchCaseCheckBox2.isSelected();
        }
        else {
            isIgnoringCase = !matchCaseCheckBox.isSelected();
        }
        int occurrences = StrTools.countOccurrences(
                tabManageObj.getSelectedTextPane().getText(),
                queryText,isIgnoringCase);
        Dialog.msgBox("Found "+occurrences+" occurrences of\n\""+queryText+
                "\" in this document.");
    }
    
    private void replaceCurrent() {
        JTextComponent currentComponent = tabManageObj.getSelectedTextPane();
        String selectedText =
                tabManageObj.getSelectedTextPane().getSelectedText();
        if (selectedText == null) {
            return;
        }
        if (selectedText.equalsIgnoreCase(query2.getText())) {
            currentComponent.replaceSelection(replaceTextField.getText());
        }
    }
    
    private void replaceAll() {
        JTextComponent currentComponent = tabManageObj.getSelectedTextPane();
        String replacementText = replaceTextField.getText();
        String targetText = query2.getText();
        if (targetText.isEmpty()) {
            return;
        }
        int targetTextLength = targetText.length();
        if (matchCaseCheckBox2.isSelected()) {
            if (targetText.equals(replacementText)) {
                return;
            }
            String text = currentComponent.getText();
            currentComponent.setText(text.replace(targetText,replacementText));
        } else {
            if (targetText.equalsIgnoreCase(replacementText)) {
                return;
            }
            String newText = currentComponent.getText();
            int position = 0;
            while (position < newText.length()) {
                position = StrTools.searchIgnoreCase(newText,position,
                        targetText);
                if (position == -1) {
                    break;
                }
                newText = StrTools.slice(newText,0,position) + replacementText +
                        StrTools.slice(newText,position+targetTextLength);
                position += targetTextLength + 1;
            }
            currentComponent.setText(newText);
        }
    }
    
    private void findAndSelectTextInTextComponent(JTextComponent component,
            String textToFind,
            boolean isWrappedDocument,boolean isCaseSensitive,
            boolean isDirectionDown) {
        int currentPosition = component.getCaretPosition();
        int foundPosition = findTextInTextComponent(component,textToFind,
                currentPosition,isWrappedDocument,
                isCaseSensitive,isDirectionDown);
        if (foundPosition == -1 && !isWrappedDocument) {
            String textBoxContents = component.getText();
            boolean doesQueryExistInDocumentIgnoringCase =
                    (!StrTools.containsIgnoreCase(textBoxContents,textToFind) &&
                    !isCaseSensitive);
            boolean doesQueryExistInDocumentWithCase =
                    (!textBoxContents.contains(textToFind) && isCaseSensitive);
            if (doesQueryExistInDocumentIgnoringCase ||
                    doesQueryExistInDocumentWithCase) {
                Dialog.msgBox("Cannot find \""+textToFind+"\" inside this\n"+
                        "this document.");
            } else {
                if (isDirectionDown) {
                    Dialog.msgBox("Reached end of document.");
                } else {
                    Dialog.msgBox("Reached beginning of document.");
                }
            }
        } else if (foundPosition == -1) {
            //We know the document must be wrapped. We really can't find the
            //text:
            Dialog.msgBox("Cannot find \""+textToFind+"\" inside this\n"+
                    "this document.");
        } else {
            //We successfully found the text. Select it:
            int endPosition = foundPosition+textToFind.length();
            //            //We must focus the textBox or else we cannot see what we will
            //            //be selecting:
            tabManageObj.focusCurrentTextPane();
            if (isDirectionDown) {
                component.setCaretPosition(foundPosition);
                component.moveCaretPosition(endPosition);
            } else {
                component.setCaretPosition(endPosition);
                component.moveCaretPosition(foundPosition);
            }
        }
    }
    
    /** Finds the specified text inside a text component. Will return -1
     * if the text is not found. */
    private int findTextInTextComponent(JTextComponent component,
            String textToFind,int startPos,boolean isWrappedDocument,
            boolean isCaseSensitive,boolean isDirectionDown) {
        int foundIndex;
        String text = component.getText();
        if (isDirectionDown) {
            if (isCaseSensitive) {
                foundIndex = StrTools.search(text,startPos,textToFind);
            }
            else {
                foundIndex = StrTools.searchIgnoreCase(text,startPos,
                        textToFind);
            }
        } else {
            int newStartPos = startPos - 1;
            if (newStartPos <= 0) {
                newStartPos = startPos;
            }
            if (isCaseSensitive) {
                foundIndex = StrTools.searchBackwards(text,newStartPos,
                        textToFind);
            } else {
                foundIndex = StrTools.searchBackwardsIgnoreCase(text,
                        newStartPos,textToFind);
            }
        }
        if (foundIndex == -1 && isWrappedDocument && isDirectionDown) {
            if (isCaseSensitive) {
                foundIndex = StrTools.search(text,0,textToFind);
            }
            else {
                foundIndex = StrTools.searchIgnoreCase(text,0,textToFind);
            }
        } else if (foundIndex == -1 && isWrappedDocument) {
            //We know that the searching is upward because we already checked
            //if it was downward and disproved that.
            if (isCaseSensitive) {
                foundIndex = StrTools.searchBackwards(text,textToFind);
            }
            else {
                foundIndex = StrTools.searchBackwardsIgnoreCase(text,
                             textToFind);
            }
        }
        return foundIndex;
    }
}
//</editor-fold>

//<editor-fold defaultstate="collapsed" desc="Private class CustomUndoableEditListener">
private class CustomUndoableEditListener implements UndoableEditListener {
    @Override
    public void undoableEditHappened(UndoableEditEvent event) {
        undoManageTeam.getCurrentManager().addEdit(event.getEdit());
    }
}//END CLASS Undoable Edit Listener
//</editor-fold>

//<editor-fold defaultstate="collapsed" desc="Private classes UndoAction and RedoAction">
private class UndoAction extends AbstractAction {
    @Override
    public void actionPerformed(ActionEvent event) {
        try {
            UndoManager currentManager = undoManageTeam.getCurrentManager();
            if (currentManager.canUndo()) {
                currentManager.undo();
            }
        } catch (CannotUndoException exceptionInfo) {
            //Ignore the exception.
        }
    }
}

private class RedoAction extends AbstractAction {
    @Override
    public void actionPerformed(ActionEvent event) {
        try {
            UndoManager currentManager = undoManageTeam.getCurrentManager();
            if (currentManager.canRedo()) {
                currentManager.redo();
            }
        } catch (CannotRedoException exceptionInfo) {
            //Ignore the exception.
        }
    }
}
//</editor-fold>

//<editor-fold defaultstate="collapsed" desc="KeyListener class">
/* private class KeyTracker extends KeyAdapter {
    @Override
    public void keyPressed(KeyEvent e) {
        System.out.println("HERP!!!!!");
    }
    
    @Override
    public void keyReleased(KeyEvent e) {
        // Do things here.
    }
} */
//</editor-fold>

//<editor-fold defaultstate="collapsed" desc="The main method (called on startup of application)">
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc="Set the application's look and feel.">
        try {
            // Set the system look and feel.
            // (Windows theme for windows, Mac theme for Macs...)
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException e) {
            // Ignore this exception. Default Java look & feel
            // will be loaded.
        } catch (ClassNotFoundException e) {
            // Ignore this exception. Default Java look & feel
            // will be loaded.
        } catch (InstantiationException e) {
            // Ignore this exception. Default Java look & feel
            // will be loaded.
        } catch (IllegalAccessException e) {
            // Ignore this exception. Default Java look & feel
            // will be loaded.
        }
        //</editor-fold>
        //<editor-fold defaultstate="collapsed" desc="Create and display the GUI.">
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LimeGui().setVisible(true);
            }
        });
        //</editor-fold>
    }
//</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeFontButton;
    private javax.swing.JFrame changeFontFrame;
    private javax.swing.JMenuItem changeFontItem;
    private javax.swing.JMenuItem closeAllTabsItem;
    private javax.swing.JMenuItem closeTabItem;
    private javax.swing.JMenuItem copyItem;
    private javax.swing.JButton countOccurrencesButton;
    private javax.swing.JButton countOccurrencesButton2;
    private javax.swing.JMenuItem cutItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JFrame findReplaceFrame;
    private javax.swing.JMenuItem findReplaceItem;
    private javax.swing.JButton findTextButton;
    private javax.swing.JButton findTextButton2;
    private javax.swing.JFrame findTextFrame;
    private javax.swing.JMenuItem findTextItem;
    private javax.swing.JTextField fontField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JCheckBox matchCaseCheckBox;
    private javax.swing.JCheckBox matchCaseCheckBox2;
    private javax.swing.JMenuItem newFileItem;
    private javax.swing.JMenuItem newTabItem;
    private javax.swing.JMenuItem openFileItem;
    private javax.swing.JMenuItem pasteItem;
    private javax.swing.JTextField query;
    private javax.swing.JTextField query2;
    private javax.swing.JMenuItem quitItem;
    private javax.swing.JButton replaceAllButton;
    private javax.swing.JButton replaceButton;
    private javax.swing.JTextField replaceTextField;
    private javax.swing.JLabel replaceWithLabel;
    private javax.swing.JMenuItem saveFileAsItem;
    private javax.swing.JMenuItem saveFileItem;
    private javax.swing.JRadioButton searchDownRadioButton;
    private javax.swing.JRadioButton searchDownRadioButton2;
    private javax.swing.JLabel searchForLabel;
    private javax.swing.JLabel searchForLabel2;
    private javax.swing.JRadioButton searchUpRadioButton;
    private javax.swing.JRadioButton searchUpRadioButton2;
    private javax.swing.JMenuItem selectAllItem;
    private javax.swing.JPopupMenu.Separator separator1;
    private javax.swing.JPopupMenu.Separator separator2;
    private javax.swing.JPopupMenu.Separator separator3;
    private javax.swing.JPopupMenu.Separator separator4;
    private javax.swing.JMenuItem switchFirstTabItem;
    private javax.swing.JMenuItem switchLastTabItem;
    private javax.swing.JMenu tabMenu;
    private javax.swing.JMenuBar topMenuBar;
    private javax.swing.JCheckBox wrapDocumentAroundCheckBox;
    private javax.swing.JCheckBox wrapDocumentAroundCheckBox2;
    // End of variables declaration//GEN-END:variables
}
